### ISSUE TITLE
Game files not updating automatically

### ISSUE THREAD

**Issue by RhymeRone** [hiperesp/DragonFable-Private-Server#88]
Game files are not updated automatically, even if I change the database to dynamic and it remains cached, it does not receive the necessary files.

}

https://github.com/user-attachments/assets/9271f96e-20a6-440a-9122-afb736d2b072

![chrome_fjFX3A9JeW](https://github.com/user-attachments/assets/e40bf9e3-370a-41f8-b623-1603e89946c8)

**Comment by hiperesp** [comment]
I fixed this dynamic mode: 9f90d36

PS: to update your game files, you need to use the `update.php` mode, like this `cdn/gamefiles/update.php/86400/`. The 86400 is the max time this file will be "cached". If DF update the swf in their servers, when requesting a specific swf, if the cache file is older than 86400 seconds (1 day), it will be requested to DF servers and the file will be saved.

The dynamic mode is when we have some local files (and patched files) and we have low disk space (or dont want to store all gamefiles)

**Comment by RhymeRone** [comment]
I updated it to update.php/8644/ as you said, and when I enter the game it gives an error saying load failed. 

I tried dynamic.php, same thing. (I applied your fix)

I can only enter the game files files by placing them in the folder beforehand.
