### ISSUE TITLE
 Ruffle causing freezing?

### ISSUE THREAD

**Issue by RhymeRone** [hiperesp/DragonFable-Private-Server#91]
Hello, I see that the game automatically runs the ruffle plugin in the browser.

![chrome_VdUIB3St50](https://github.com/user-attachments/assets/2a18c10c-0641-48b3-9542-af518ab4f343)

But the game has a very low fps rate. I tried the Ruffle desktop version, it is a little better but it lags.

Instead, I installed Pale Moon, an old browser, and the Adobe Flash Player plug-in. Here is the result

https://github.com/user-attachments/assets/77b91888-6311-4798-9d23-e74e5e4c31fb

It has high fps rate, (Just the colors are a little weird :D) 
this old browser uses adobe flash player instead of running ruffle.

![nKnFuqGpai](https://github.com/user-attachments/assets/6f837a58-f120-4191-8a34-e8825a205ef1)

Is it possible that we can choose to disable this if ruffle is run by the game? or ruffle / adobe preference?

**Comment by hiperesp** [comment]
I was wrong... By default, ruffle is only enabled if browser is incompatible with flash player.
I tested with palemoon and adobe flash player is used.
I tested with basilisk (custom, with adobe flash player), and worked like palemoon.
Recent chrome / firefox is incompatible with adobe flash player and there is no way to enable it. Ruffle is used.

**Comment by RhymeRone** [comment]
So can't a new launcher be built?

As far as I remember, trainers were made for Dragon Fable and these trainers worked with high fps rates, such as Artix game launcher..

Do you think it is possible to build a launcher that works with high fps rates to connect to our own server?

**Comment by hiperesp** [comment]
Yes, this is possible. I don't know exactly how Artix Game Launcher works, but it's simple to create a launcher in a similar way.

I think Artix Game Launcher is basically a electronjs app with built-in flash (I haven't seen the files, it's just a guess). In fact, the launcher open this url https://artix.com/gamelauncher/ and do some internal javascript calls.

But creating a specific launcher is a bit far from my proposal with this repo.
